//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 04:15:11 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ejb.service.webservice.jaas.security.rumba.med.ge.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mypacs.wsdl;
